services:
  postgres:
    image: postgres:16
    container_name: keria_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: ./backend
    container_name: keria_backend
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: